name: ReactTodo workflow

on:
  push:
    branches:
    - main
    - features/**

jobs:
  demo:
    name: demo job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      
    - name: setup node.js
      run: |
        curl -s https://deb.nodesource.com/setup_16.x | sudo bash
        sudo apt install nodejs -y
      
    - name: install dependancy
      run: npm install
    
    - name: build
      run: npm run build   

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0  
      with:
        name: build-${{GITHUB.RUN_ID}}
        path: build
    - name: Download a Build Artifact
      uses: actions/download-artifact@v7.0.0
      with:
        name: build-${{github.repository}}
        path: build
        
      
  
